name: Validate Code

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Test with Node.js v14 (LTS), v16 (LTS), and v18
        node: [14.x, 16.x, 18.x]

    steps:
      - name: ðŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: install dependencies
        run: npm install --no-save

      - run: npm run build

      - name: lint js
        run: npm run lint

      - name: run tests
        run: npm run test
        env:
          CI: true

  pr-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: install dependencies
        run: npm install --no-save

      - run: npm run build

      - name: publish to npm
        id: pr-publish
        run: |
          version="0.0.0-PR-${PR}--$(echo ${SHA} | cut -c -7)"
          npm version $version --no-git-tag-version
          npm publish --access public --tag pr
          echo "::set-output name=pr_version::$version"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PR: ${{ github.event.number }}
          SHA: ${{ github.event.pull_request.head.sha }}

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ðŸš€ PR version published: `${{ steps.pr-publish.outputs.pr_version }}`'
            })
